
import __ASTRO_IMAGE_IMPORT_Z1vfoLd from "../../assets/images/about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fabout.md";
import __ASTRO_IMAGE_IMPORT_Z26S59R from "../../assets/images/post-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fadvantages-disadvantages-of-working-from-home.md";
import __ASTRO_IMAGE_IMPORT_Z13AIsE from "../../assets/images/post-8.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuilding-an-impressive-front-end-developer-portfolio.md";
import __ASTRO_IMAGE_IMPORT_Z23Y0t2 from "../../assets/images/post-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcommunication-and-collaboration-for-front-end-developers.md";
import __ASTRO_IMAGE_IMPORT_Z25XCT4 from "../../assets/images/post-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fexploring-the-future-of-front-end-development.md";
import __ASTRO_IMAGE_IMPORT_1TEhW5 from "../../assets/images/post-9.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fevolution-of-front-end-development.md";
import __ASTRO_IMAGE_IMPORT_1EG3kO from "../../assets/images/post-6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fultimate-front-end-developer-career-roadmap.md";
import __ASTRO_IMAGE_IMPORT_1k0Hh4 from "../../assets/images/post-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffront-end-techniques-for-optimizing-website-performance.md";
import __ASTRO_IMAGE_IMPORT_Z1UH69U from "../../assets/images/post-5-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fyour-roadmap-to-framework-selection-success.md";
import __ASTRO_IMAGE_IMPORT_Z1DY7T9 from "../../assets/images/post-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fyour-roadmap-to-framework-selection-success.md";
import __ASTRO_IMAGE_IMPORT_Z2i9fxB from "../../assets/images/post-7.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Funleashing-the-power-of-tailwind-css.md";
export default new Map([["../../assets/images/about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fabout.md", __ASTRO_IMAGE_IMPORT_Z1vfoLd], ["../../assets/images/post-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fadvantages-disadvantages-of-working-from-home.md", __ASTRO_IMAGE_IMPORT_Z26S59R], ["../../assets/images/post-8.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuilding-an-impressive-front-end-developer-portfolio.md", __ASTRO_IMAGE_IMPORT_Z13AIsE], ["../../assets/images/post-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcommunication-and-collaboration-for-front-end-developers.md", __ASTRO_IMAGE_IMPORT_Z23Y0t2], ["../../assets/images/post-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fexploring-the-future-of-front-end-development.md", __ASTRO_IMAGE_IMPORT_Z25XCT4], ["../../assets/images/post-9.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fevolution-of-front-end-development.md", __ASTRO_IMAGE_IMPORT_1TEhW5], ["../../assets/images/post-6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fultimate-front-end-developer-career-roadmap.md", __ASTRO_IMAGE_IMPORT_1EG3kO], ["../../assets/images/post-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffront-end-techniques-for-optimizing-website-performance.md", __ASTRO_IMAGE_IMPORT_1k0Hh4], ["../../assets/images/post-5-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fyour-roadmap-to-framework-selection-success.md", __ASTRO_IMAGE_IMPORT_Z1UH69U], ["../../assets/images/post-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fyour-roadmap-to-framework-selection-success.md", __ASTRO_IMAGE_IMPORT_Z1DY7T9], ["../../assets/images/post-7.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Funleashing-the-power-of-tailwind-css.md", __ASTRO_IMAGE_IMPORT_Z2i9fxB]]);
		